<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UnsrcSimpleAuth\Module'                            => __DIR__ . '/Module.php',
    'UnsrcSimpleAuth\Plugin\IsLoggedInControllerPlugin' => __DIR__ . '/src/UnsrcSimpleAuth/Plugin/IsLoggedInControllerPlugin.php',
    'UnsrcSimpleAuth\Plugin\IsLoggedInViewHelper'       => __DIR__ . '/src/UnsrcSimpleAuth/Plugin/IsLoggedInViewHelper.php',
    'UnsrcSimpleAuth\Plugin\GetIdentityViewHelper'      => __DIR__ . '/src/UnsrcSimpleAuth/Plugin/GetIdentityViewHelper.php',
    'UnsrcSimpleAuth\Authentication\AuthAdapter'        => __DIR__ . '/src/UnsrcSimpleAuth/Authentication/AuthAdapter.php',
    'UnsrcSimpleAuth\Controller\LoginController'        => __DIR__ . '/src/UnsrcSimpleAuth/Controller/LoginController.php',
    'UnsrcSimpleAuth\Form\LoginForm'                    => __DIR__ . '/src/UnsrcSimpleAuth/Form/LoginForm.php',
    'UnsrcSimpleAuth\Form\LoginFilter'                  => __DIR__ . '/src/UnsrcSimpleAuth/Form/LoginFilter.php',
);
